/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // basicsSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Basics',
  //     items: [
  //       {
  //         type: 'doc',
  //         id: 'basics/intro',
  //       },
  //       {
  //         type: 'category',
  //         label: 'OOP',
  //         items: ['basics/OOP/intro'],
  //       },
  //     ],
  //   },
  // ],
  basicsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'basics',
    },
  ],
  problemsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'problems',
      // type: 'category',
      // label: 'Leetcode',
      // items: [
      //   {
      //     type: 'doc',
      //     id: 'problems/intro',
      //   },
      // ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
